-- ─── MIGRACIÓN DE LA TABLA MIEMBROS ──────────────────────────────────────────
-- Ejecuta este script en el SQL Editor de tu panel de Supabase.
-- ¡ATENCIÓN!: Esto borrará la tabla miembros anterior y recreará la estructura. Respaldar antes si es necesario.

DROP TABLE IF EXISTS public.miembros CASCADE;

CREATE TABLE public.miembros (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discord_id varchar(50) UNIQUE NOT NULL,
  nombre_completo text NOT NULL,
  correo_institucional text UNIQUE NOT NULL,
  rol_lead text NOT NULL,
  estado varchar(30) NOT NULL DEFAULT 'PENDIENTE',
  aprobado_por varchar(50),
  creado_en timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Asegurar que RLS esté habilitado en la tabla 'miembros'
ALTER TABLE public.miembros ENABLE ROW LEVEL SECURITY;

-- ─── POLÍTICAS DE SEGURIDAD (RLS) ─────────────────────────────────────────────

-- 1. Permitir lectura total de la tabla a usuarios autenticados
CREATE POLICY "Permitir lectura de miembros a usuarios autenticados"
ON public.miembros FOR SELECT TO authenticated USING (true);

-- 2. Permitir inserción a usuarios autenticados (necesario para el onboarding)
CREATE POLICY "Permitir inserción de miembros a usuarios autenticados"
ON public.miembros FOR INSERT TO authenticated WITH CHECK (true);

-- 3. Permitir actualización a usuarios autenticados (para que admins aprueben y bot marque verificado)
CREATE POLICY "Permitir actualización de miembros a usuarios autenticados"
ON public.miembros FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- 4. Permitir eliminación a usuarios autenticados
CREATE POLICY "Permitir eliminación de miembros a usuarios autenticados"
ON public.miembros FOR DELETE TO authenticated USING (true);

-- 5. Permitir lectura de miembros verificados al público general (anon) para la landing page
CREATE POLICY "Permitir lectura de miembros verificados al público"
ON public.miembros FOR SELECT TO anon USING (estado = 'VERIFICADO');
